### ISSUE TITLE
[STYLE] Update Products Section

### ISSUE THREAD

**Issue by AliMora83** [chingu-voyages/v44-tier3-team-41#39]
**__Task Description__**
- Update Products Section

**__Technical Considerations__**
- None

**__Additional Considerations__**
Current:
<img width="1604" alt="Screenshot 2023-05-23 at 17 41 02" src="https://github.com/chingu-voyages/v44-tier3-team-41/assets/56822813/6b3cd068-e5a8-49cd-ae60-de7ce1cd67c1">

**Comment by AliMora83** [comment]
Very Good 🥳

**Comment by AliMora83** [comment]
Updates made:
<img width="1585" alt="Screenshot 2023-05-23 at 19 02 27" src="https://github.com/chingu-voyages/v44-tier3-team-41/assets/56822813/6bea7aa2-1dce-4cb8-9282-2303a91944aa">

Will connect links to products later.

**Comment by alexh205** [comment]
Can I ask, what is the plan for the 'Explore all courses' button? what will be linked here (currently the backend is not designed to handle any new products)?

**Comment by AliMora83** [comment]
That can be linked to any page we want or even removed. 
In our next meet we can discuss all nav and social links👍🏼
